name: deploy

on:
  push:
    branches:
    - master

jobs:
  delpoy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - run: npm ci

    - run: npm run build

    - name: rsync deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: dist/
        remote_path: /var/www/vhosts/plesk.tech/httpdocs
        remote_host: plesk.tech
        remote_user: plesktech
        remote_key: ${{ secrets.DEPLOY_KEY }}

    - name: gh-pages deployment
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./dist
